services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: veryhardpassword
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  outfitcontrol:
    image: outfitcontrol
    ports:
      - 80:8080
    build:
      context: .
      dockerfile: OutfitControl/Dockerfile
    networks:
      - app_network
    depends_on:
      - db

networks:
  app_network:
    driver: bridge